# Generated by Django 4.1.5 on 2023-01-23 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='trainer_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('middlename', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('box_number', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='teacher/passport/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_trainer', models.BooleanField(default=True, editable=False)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('trainer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trainer Profile',
                'verbose_name_plural': 'Trainer Profiles',
            },
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('middlename', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('box_number', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='students/passport/')),
                ('kcse_cert', models.FileField(upload_to='students/kcse/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_student', models.BooleanField(default=True, editable=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='guardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('middlename', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('box_number', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
            },
        ),
    ]
