# Generated by Django 4.1.4 on 2023-01-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='is_student',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='trainer_profile',
            name='is_trainer',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
