# Generated by Django 4.1.4 on 2023-01-17 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_student_profile_box_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer_profile',
            old_name='teacher_id',
            new_name='trainer_id',
        ),
    ]
