# Generated by Django 4.1.4 on 2023-01-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_teacher_id_trainer_profile_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='middlename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
