# Generated by Django 4.1.4 on 2023-01-17 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0005_alter_student_profile_middlename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_profile',
            old_name='Box_number',
            new_name='box_number',
        ),
        migrations.RenameField(
            model_name='student_profile',
            old_name='Postal_code',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='trainer_profile',
            old_name='Box_number',
            new_name='box_number',
        ),
        migrations.RenameField(
            model_name='trainer_profile',
            old_name='Postal_code',
            new_name='postal_code',
        ),
        migrations.AlterField(
            model_name='trainer_profile',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.student_profile'),
        ),
        migrations.CreateModel(
            name='guardianInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('middlename', models.CharField(blank=True, max_length=150, null=True)),
                ('lastname', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('contact', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('box_number', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
            },
        ),
    ]
