# Generated by Django 4.1.5 on 2023-01-23 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0006_rename_box_number_student_profile_box_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_profile',
            name='trainer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
