# Generated by Django 4.1.5 on 2023-01-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_trainer_profile_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trainer_profile',
            name='is_trainer',
            field=models.BooleanField(default=True),
        ),
    ]
