# Generated by Django 4.1.5 on 2023-01-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_student_profile_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='is_student',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='trainer_profile',
            name='is_trainer',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
