# Generated by Django 4.1.5 on 2023-01-23 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0009_alter_student_profile_is_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer_profile',
            name='trainer_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
