# Generated by Django 4.1.4 on 2022-12-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latest',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'latest'},
        ),
    ]
