# Generated by Django 4.1.4 on 2022-12-21 21:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_upcoming'),
    ]

    operations = [
        migrations.AddField(
            model_name='latest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/latest'),
        ),
        migrations.AddField(
            model_name='upcoming',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/latest'),
        ),
        migrations.AlterField(
            model_name='latest',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
