# Generated by Django 4.1.4 on 2022-12-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_latest_image_upcoming_image_alter_latest_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/latest'),
        ),
        migrations.AlterField(
            model_name='upcoming',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/upcoming'),
        ),
    ]
