# Generated by Django 4.1.4 on 2023-01-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='title',
            field=models.CharField(default='home', max_length=50),
            preserve_default=False,
        ),
    ]
