# Generated by Django 4.1.4 on 2022-12-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_board_of_governor_principal_statement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board_of_governor',
            options={'verbose_name_plural': 'Board of Governors'},
        ),
        migrations.AlterField(
            model_name='board_of_governor',
            name='image',
            field=models.ImageField(upload_to='images/bog'),
        ),
    ]
