# Generated by Django 4.1.4 on 2022-12-21 18:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_board_of_governor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='images/dean')),
            ],
        ),
    ]
