# Generated by Django 4.1.4 on 2022-12-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_dean'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dean',
            options={'verbose_name_plural': 'Dean of Students'},
        ),
    ]
