# Generated by Django 4.1.4 on 2022-12-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_dean_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_charter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('charter', models.FileField(upload_to='charter/')),
            ],
            options={
                'verbose_name_plural': 'Service Charter',
            },
        ),
    ]
