# Generated by Django 4.1.5 on 2023-01-30 13:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField()),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
