# Generated by Django 4.1.4 on 2022-12-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='file',
            field=models.FileField(upload_to='documents/careers/'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='file',
            field=models.FileField(upload_to='documents/internship/'),
        ),
    ]
