# Generated by Django 4.1.4 on 2023-01-16 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='online_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=150)),
                ('firstname', models.CharField(max_length=150)),
                ('middlename', models.CharField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('contact', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('kcse_certificate', models.FileField(upload_to='documents/KCSE/')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.course')),
            ],
            options={
                'verbose_name_plural': 'Registered Online',
                'ordering': ('-registered_at',),
            },
        ),
    ]
