# Generated by Django 4.1.4 on 2023-01-06 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='online_registration',
            options={'ordering': ('-registered_at',)},
        ),
        migrations.AddField(
            model_name='online_registration',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
