# Generated by Django 4.1.4 on 2023-01-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_online_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='online_registration',
            options={'ordering': ('-registered_at',), 'verbose_name_plural': 'Registered Online'},
        ),
    ]
