# Generated by Django 4.1.4 on 2022-12-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_department_name_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='department',
        ),
    ]
