# Generated by Django 4.1.4 on 2023-01-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_message_department_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department_message',
            name='title',
        ),
        migrations.AddField(
            model_name='department_message',
            name='display_image',
            field=models.ImageField(default='department/image/ict_session.JPG', upload_to='department/image'),
        ),
    ]
