# Generated by Django 4.1.4 on 2023-01-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_message_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department_message',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department_message',
            name='display_image',
            field=models.ImageField(default='', upload_to='department/image'),
        ),
    ]
