# Generated by Django 4.1.4 on 2022-12-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_rename_course_code_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='module',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
