# Generated by Django 4.1.4 on 2022-12-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_course_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_body',
            field=models.CharField(choices=[('KNEC', 'KNEC'), ('NITA', 'NITA'), ('KASNEB', 'KASNEB')], max_length=50),
        ),
    ]
